(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const css=`
.apoc-onboard{position:fixed;inset:0;z-index:200;background:rgba(8,12,17,.72);backdrop-filter:blur(22px) saturate(90%);display:flex;align-items:center;justify-content:center;opacity:0;pointer-events:none;transition:opacity .65s ease}.apoc-onboard.open{opacity:1;pointer-events:auto}.apoc-onboard:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 48%,rgba(111,148,184,.12),transparent 29%),radial-gradient(circle at 42% 55%,rgba(228,138,174,.09),transparent 34%);animation:obPulse 5s ease-in-out infinite alternate}@keyframes obPulse{to{transform:scale(1.1);opacity:.72}}
.ob-shell{position:relative;width:min(900px,90vw);max-height:86vh;overflow:auto;padding:46px 52px 40px;color:#e6e2da}.ob-intro{text-align:center;transition:.7s cubic-bezier(.16,.84,.32,1)}.ob-logo{font:600 clamp(28px,4.4vw,58px)/1 Consolas,monospace;letter-spacing:.22em;text-indent:.22em;text-shadow:0 0 38px rgba(111,148,184,.25)}.ob-logo i{display:inline-block;width:8px;height:8px;border-radius:50%;margin:0 13px 7px 0;background:#e48aae;box-shadow:0 0 20px #e48aae}.ob-slogan{margin-top:17px;color:#747a80;font:10px Consolas,monospace;letter-spacing:.32em}.ob-intro.shift{text-align:left;transform:translateY(-4px)}.ob-intro.shift .ob-logo{font-size:18px;letter-spacing:.16em;text-indent:0}.ob-intro.shift .ob-logo i{width:6px;height:6px;margin:0 9px 2px 0}.ob-intro.shift .ob-slogan{margin-top:7px;font-size:8px;letter-spacing:.18em}
.ob-flow{opacity:0;transform:translateY(24px);transition:.7s .12s cubic-bezier(.16,.84,.32,1)}.ob-flow.show{opacity:1;transform:none}.ob-step{display:grid;grid-template-columns:155px 1fr;gap:24px;padding:22px 0;border-top:1px solid rgba(255,255,255,.065)}.ob-k{color:#747a80;font:9px Consolas,monospace;letter-spacing:.14em}.ob-k b{display:block;margin-bottom:6px;color:#6f94b8;font-weight:500}.ob-body{min-width:0}.ob-note{color:#747a80;font:9px/1.6 Consolas,monospace;margin-bottom:11px}.ob-agents{display:flex;flex-wrap:wrap;gap:7px}.ob-agent{padding:7px 9px;border-left:2px solid rgba(111,148,184,.42);background:rgba(255,255,255,.018);font:9px Consolas,monospace;color:#b8bdc2}.ob-agent small{margin-left:7px;color:#747a80}
.ob-choice{display:flex;align-items:center;gap:11px;width:100%;padding:10px 4px;border:0;border-bottom:1px solid rgba(255,255,255,.04);background:transparent;text-align:left;color:#b8bdc2;cursor:pointer;transition:.18s}.ob-choice:hover{padding-left:9px;background:linear-gradient(90deg,rgba(111,148,184,.06),transparent)}.ob-choice i{width:9px;height:9px;border:1px solid #747a80;border-radius:2px}.ob-choice.on i{border-color:#e48aae;background:#e48aae;box-shadow:0 0 14px rgba(228,138,174,.42)}.ob-choice b{font:10px Consolas,monospace;font-weight:500}.ob-choice small{margin-left:auto;color:#747a80;font:8px Consolas,monospace}.ob-provider.on{color:#e6e2da}.ob-provider.on i{border-radius:50%;background:#6f94b8;border-color:#6f94b8;box-shadow:0 0 14px rgba(111,148,184,.5)}
.ob-model{margin-top:12px;display:flex;gap:8px;align-items:center}.ob-model select,.ob-model input,.ob-gproxy input{height:36px;border:1px solid rgba(111,148,184,.18);border-radius:6px;outline:0;background:rgba(8,12,17,.55);color:#e6e2da;padding:0 10px;font:9px Consolas,monospace}.ob-model select{min-width:290px}.ob-model input{min-width:290px}.ob-gproxy{display:grid;grid-template-columns:1.5fr .7fr 1fr;gap:7px;margin-top:10px}.ob-gproxy label{display:flex;flex-direction:column;gap:5px;color:#747a80;font:8px Consolas,monospace}.ob-gproxy input{width:100%;min-width:0}.ob-gproxy.hidden{display:none}
.ob-bottom{display:flex;align-items:center;gap:14px;padding-top:20px;border-top:1px solid rgba(255,255,255,.065)}.ob-status{flex:1;min-height:20px;color:#747a80;font:9px/1.5 Consolas,monospace}.ob-status.err{color:#f3a1bd}.ob-status.ok{color:#6f94b8}.ob-enter{height:38px;padding:0 18px;border:1px solid rgba(111,148,184,.32);border-radius:7px;background:rgba(111,148,184,.08);color:#e6e2da;font:9px Consolas,monospace;letter-spacing:.12em}.ob-enter:hover{background:rgba(111,148,184,.15);box-shadow:0 0 28px rgba(111,148,184,.1)}.ob-enter:disabled{opacity:.38;cursor:default}.ob-close{position:absolute;right:30px;top:28px;border:0;background:transparent;color:#747a80;font-size:20px;display:none}.apoc-onboard.reconfigure .ob-close{display:block}
@media(max-width:700px){.ob-shell{padding:32px 24px}.ob-step{grid-template-columns:1fr;gap:8px}.ob-gproxy{grid-template-columns:1fr}.ob-model select,.ob-model input{width:100%;min-width:0}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const root=document.createElement('div');root.className='apoc-onboard';root.innerHTML=`<div class="ob-shell"><button class="ob-close" title="Close">×</button><div class="ob-intro"><div class="ob-logo"><i></i>APOCALYPSE</div><div class="ob-slogan">YOUR AGENTS. ONE MEMORY.</div></div><div class="ob-flow"><div id="obContent"><div class="ob-step"><div class="ob-k"><b>ENVIRONMENT</b>DISCOVERY</div><div class="ob-body"><div class="ob-note">SCANNING LOCAL AGENTS / PROVIDERS / MODELS…</div></div></div></div></div></div>`;document.body.appendChild(root);
const intro=root.querySelector('.ob-intro'),flow=root.querySelector('.ob-flow'),content=root.querySelector('#obContent'),closeBtn=root.querySelector('.ob-close');
let discovery=null,reconfigure=false,selectedPlans=new Set(),candidateId='';
function status(t,k=''){const el=root.querySelector('.ob-status');if(el){el.className='ob-status'+(k?' '+k:'');el.textContent=t||''}}
function candidate(){return (discovery?.providers||[]).find(x=>x.id===candidateId)}
function render(){
 selectedPlans=new Set((discovery.current?.quota_plans||[]).filter(x=>(discovery.plans||[]).some(p=>p.name===x)));
 if(!selectedPlans.size)(discovery.plans||[]).forEach(p=>selectedPlans.add(p.name));
 candidateId=discovery.current?.analysis_candidate || discovery.providers?.[0]?.id || '';
 const c=candidate();
 content.innerHTML=`
 <div class="ob-step"><div class="ob-k"><b>ENVIRONMENT</b>DETECTED</div><div class="ob-body"><div class="ob-agents">${(discovery.agents||[]).length?(discovery.agents||[]).map(a=>`<span class="ob-agent">${esc(a.name)}<small>${esc(a.version||'installed')}</small></span>`).join(''):'<span class="ob-note">NO SUPPORTED AGENT FOUND ON PATH</span>'}</div></div></div>
 <div class="ob-step"><div class="ob-k"><b>LLM QUOTA</b>DASHBOARD</div><div class="ob-body"><div class="ob-note">Choose the Plan usage rows Apocalypse should keep visible.</div><div id="obPlans">${(discovery.plans||[]).map(p=>`<button class="ob-choice ${selectedPlans.has(p.name)?'on':''}" data-plan="${esc(p.name)}"><i></i><b>${esc(p.name)}</b><small>${esc((p.sources||[]).join(' / ').toUpperCase())} · ${esc((p.availability||'').toUpperCase())}</small></button>`).join('')||'<div class="ob-note">NO PLAN USAGE SOURCE DETECTED</div>'}</div></div></div>
 <div class="ob-step"><div class="ob-k"><b>ANALYSIS</b>HARNESS</div><div class="ob-body"><div class="ob-note">Choose the provider path and model Apocalypse will use for workspace, agenda and agent-worklog analysis.</div><div id="obProviders">${(discovery.providers||[]).map(p=>`<button class="ob-choice ob-provider ${p.id===candidateId?'on':''}" data-provider="${esc(p.id)}"><i></i><b>${esc(p.provider)}</b><small>${esc((p.source_agent||'').toUpperCase())} · ${esc((p.transport||'').toUpperCase())}</small></button>`).join('')||'<div class="ob-note">NO USABLE ANALYSIS PROVIDER DETECTED</div>'}</div><div class="ob-model" id="obModel"></div></div></div>
 <div class="ob-step"><div class="ob-k"><b>USAGE SOURCE</b>GPROXY</div><div class="ob-body"><div class="ob-note">Optional. Keep the detected values or provide your GProxy admin login for live 5H / WEEKLY quota cycles. The password stays on this machine.</div><div class="ob-gproxy ${selectedPlans.size?'':'hidden'}" id="obGproxy"><label>BASE URL<input id="obGpBase" value="${esc(discovery.gproxy?.base_url||'')}" placeholder="https://…"></label><label>USERNAME<input id="obGpUser" value="${esc(discovery.gproxy?.username||'admin')}"></label><label>PASSWORD<input id="obGpPass" type="password" placeholder="${discovery.gproxy?.has_password?'saved · leave blank to keep':'optional'}"></label></div></div></div>
 <div class="ob-bottom"><div class="ob-status"></div><button class="ob-enter" id="obEnter">${reconfigure?'APPLY CONFIGURATION':'ENTER APOCALYPSE'}</button></div>`;
 content.querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>{const n=b.dataset.plan;selectedPlans.has(n)?selectedPlans.delete(n):selectedPlans.add(n);b.classList.toggle('on',selectedPlans.has(n));content.querySelector('#obGproxy')?.classList.toggle('hidden',!selectedPlans.size)});
 content.querySelectorAll('[data-provider]').forEach(b=>b.onclick=()=>{candidateId=b.dataset.provider;content.querySelectorAll('[data-provider]').forEach(x=>x.classList.toggle('on',x.dataset.provider===candidateId));renderModel()});
 renderModel();content.querySelector('#obEnter').onclick=submit;
 }
function renderModel(){const box=content.querySelector('#obModel'),c=candidate();if(!box)return;if(!c){box.innerHTML='<span class="ob-note">SELECT A PROVIDER</span>';return}const models=(c.models||[]).filter(Boolean);if(models.length){box.innerHTML=`<select id="obModelValue">${models.map(m=>`<option ${m===discovery.current?.analysis_model&&c.id===discovery.current?.analysis_candidate?'selected':''}>${esc(m)}</option>`).join('')}</select>`}else box.innerHTML='<input id="obModelValue" placeholder="MODEL ID">'}
async function submit(){const btn=content.querySelector('#obEnter'),model=(content.querySelector('#obModelValue')?.value||'').trim();if(!candidateId||!model){status('SELECT AN ANALYSIS PROVIDER AND MODEL','err');return}btn.disabled=true;status('VERIFYING ANALYSIS HARNESS…');const payload={quota_plans:[...selectedPlans],analysis_candidate:candidateId,analysis_model:model,gproxy:{base_url:content.querySelector('#obGpBase')?.value||'',username:content.querySelector('#obGpUser')?.value||'',password:content.querySelector('#obGpPass')?.value||''}};try{const r=await fetch('/api/onboarding/complete',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok||j.ok===false)throw new Error(j.error||`HTTP ${r.status}`);status('HARNESS VERIFIED · CONFIGURATION SAVED','ok');setTimeout(()=>{root.classList.remove('open');try{if(typeof refreshAll==='function')refreshAll()}catch{}},650)}catch(e){status('SETUP FAILED · '+e.message,'err');btn.disabled=false}}
async function open(force=false){reconfigure=force;root.classList.toggle('reconfigure',force);root.classList.add('open');intro.classList.remove('shift');flow.classList.remove('show');content.innerHTML='<div class="ob-step"><div class="ob-k"><b>ENVIRONMENT</b>DISCOVERY</div><div class="ob-body"><div class="ob-note">SCANNING LOCAL AGENTS / PROVIDERS / MODELS…</div></div></div>';await new Promise(r=>setTimeout(r,force?180:1050));intro.classList.add('shift');flow.classList.add('show');try{const r=await fetch('/api/onboarding/discover',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);discovery=j;render()}catch(e){content.innerHTML=`<div class="ob-step"><div class="ob-k"><b>DISCOVERY</b>FAILED</div><div class="ob-body"><div class="ob-note" style="color:#f3a1bd">${esc(e.message)}</div></div></div>`}}
closeBtn.onclick=()=>{if(reconfigure)root.classList.remove('open')};
window.ApocalypseOnboarding={open};
const oldReinit=document.getElementById('reinitBtn');if(oldReinit)oldReinit.onclick=e=>{e.stopPropagation();document.querySelector('.settings-menu')?.classList.remove('open');open(true)};
(async()=>{try{const r=await fetch('/api/onboarding/status',{cache:'no-store'}),j=await r.json();if(!j.initialized)open(false)}catch(e){console.warn('Apocalypse onboarding status unavailable',e)}})();
})();
